# Generated by Django 3.2 on 2023-02-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='User name')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(default='ACTIVE', max_length=100, verbose_name='Status')),
            ],
        ),
    ]
